/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/nourspeed/provider-libvirt/apis/cloudinit/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Domain.
func (mg *Domain) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Cloudinit),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.CloudinitRef,
		Selector:     mg.Spec.ForProvider.CloudinitSelector,
		To: reference.To{
			List:    &v1alpha1.DiskList{},
			Managed: &v1alpha1.Disk{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Cloudinit")
	}
	mg.Spec.ForProvider.Cloudinit = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CloudinitRef = rsp.ResolvedReference

	return nil
}
