apiVersion: cloudinit.nourspeed.io/v1alpha1
kind: Disk
metadata:
  name: commoninit
spec:
  forProvider:
    name: "commoninit.iso"
    pool: cluster-crossplane
    userData: |
      #cloud-config
      # vim: syntax=yaml
      #
      # ***********************
      # 	---- for more examples look at: ------
      # ---> https://cloudinit.readthedocs.io/en/latest/topics/examples.html
      # ******************************
      #
      # This is the configuration syntax that the write_files module
      # will know how to understand. encoding can be given b64 or gzip or (gz+b64).
      # The content will be decoded accordingly and then written to the path that is
      # provided.
      #
      # Note: Content strings here are truncated for example purposes.
      ssh_pwauth: True
      chpasswd:
        list: |
           root: test
        expire: False
      
      users:
        - name: <username>
          ssh_authorized_keys:
            - ssh-rsa <ssh-public-key>
          sudo: ['ALL=(ALL) NOPASSWD:ALL']
          shell: /bin/bash
          groups: wheel
  providerConfigRef:
    name: default