// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/nourspeed/provider-libvirt/apis/cloudinit/v1alpha1"
	v1alpha1domain "github.com/nourspeed/provider-libvirt/apis/domain/v1alpha1"
	v1alpha1network "github.com/nourspeed/provider-libvirt/apis/network/v1alpha1"
	v1alpha1pool "github.com/nourspeed/provider-libvirt/apis/pool/v1alpha1"
	v1alpha1apis "github.com/nourspeed/provider-libvirt/apis/v1alpha1"
	v1beta1 "github.com/nourspeed/provider-libvirt/apis/v1beta1"
	v1alpha1volume "github.com/nourspeed/provider-libvirt/apis/volume/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1domain.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1pool.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1volume.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
