/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/nourspeed/provider-libvirt/apis/pool/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Volume.
func (mg *Volume) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Pool),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PoolRef,
		Selector:     mg.Spec.ForProvider.PoolSelector,
		To: reference.To{
			List:    &v1alpha1.PoolList{},
			Managed: &v1alpha1.Pool{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Pool")
	}
	mg.Spec.ForProvider.Pool = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PoolRef = rsp.ResolvedReference

	return nil
}
