// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VolumeInitParameters struct {
	BaseVolumeID *string `json:"baseVolumeId,omitempty" tf:"base_volume_id,omitempty"`

	BaseVolumeName *string `json:"baseVolumeName,omitempty" tf:"base_volume_name,omitempty"`

	BaseVolumePool *string `json:"baseVolumePool,omitempty" tf:"base_volume_pool,omitempty"`

	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	XML []XMLInitParameters `json:"xml,omitempty" tf:"xml,omitempty"`
}

type VolumeObservation struct {
	BaseVolumeID *string `json:"baseVolumeId,omitempty" tf:"base_volume_id,omitempty"`

	BaseVolumeName *string `json:"baseVolumeName,omitempty" tf:"base_volume_name,omitempty"`

	BaseVolumePool *string `json:"baseVolumePool,omitempty" tf:"base_volume_pool,omitempty"`

	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	XML []XMLObservation `json:"xml,omitempty" tf:"xml,omitempty"`
}

type VolumeParameters struct {

	// +kubebuilder:validation:Optional
	BaseVolumeID *string `json:"baseVolumeId,omitempty" tf:"base_volume_id,omitempty"`

	// +kubebuilder:validation:Optional
	BaseVolumeName *string `json:"baseVolumeName,omitempty" tf:"base_volume_name,omitempty"`

	// +kubebuilder:validation:Optional
	BaseVolumePool *string `json:"baseVolumePool,omitempty" tf:"base_volume_pool,omitempty"`

	// +kubebuilder:validation:Optional
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/nourspeed/provider-libvirt/apis/pool/v1alpha1.Pool
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a Pool in pool to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v1.Reference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a Pool in pool to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v1.Selector `json:"poolSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// +kubebuilder:validation:Optional
	XML []XMLParameters `json:"xml,omitempty" tf:"xml,omitempty"`
}

type XMLInitParameters struct {
	Xslt *string `json:"xslt,omitempty" tf:"xslt,omitempty"`
}

type XMLObservation struct {
	Xslt *string `json:"xslt,omitempty" tf:"xslt,omitempty"`
}

type XMLParameters struct {

	// +kubebuilder:validation:Optional
	Xslt *string `json:"xslt,omitempty" tf:"xslt,omitempty"`
}

// VolumeSpec defines the desired state of Volume
type VolumeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VolumeInitParameters `json:"initProvider,omitempty"`
}

// VolumeStatus defines the observed state of Volume.
type VolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Volume is the Schema for the Volumes API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,libvirt}
type Volume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VolumeSpec   `json:"spec"`
	Status VolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VolumeList contains a list of Volumes
type VolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Volume `json:"items"`
}

// Repository type metadata.
var (
	Volume_Kind             = "Volume"
	Volume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Volume_Kind}.String()
	Volume_KindAPIVersion   = Volume_Kind + "." + CRDGroupVersion.String()
	Volume_GroupVersionKind = CRDGroupVersion.WithKind(Volume_Kind)
)

func init() {
	SchemeBuilder.Register(&Volume{}, &VolumeList{})
}
